name: physical_exercise_timer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_lock_windows:
    git:
      url: https://github.com/guchengxi1994/auto_lock_windows
  window_manager: ^0.3.8
  rounded_loading_button: ^2.1.0
  percent_indicator: ^4.2.3
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  duration_picker: ^1.1.1
  shared_preferences: ^2.2.2
  toastification: ^1.2.0
  group_button: ^5.3.4

dependency_overrides: 
  auto_lock_windows: 
    git:
      url: https://gitee.com/guchengxi1994/auto_lock_windows


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true