// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/detector.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'yolo/utils.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  PoseState dco_decode_box_autoadd_pose_state(dynamic raw);

  @protected
  (Uint8List, List<PoseState>)
      dco_decode_box_autoadd_record_list_prim_u_8_strict_list_pose_state(
          dynamic raw);

  @protected
  List<PoseState> dco_decode_list_pose_state(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  (Uint8List, List<PoseState>)?
      dco_decode_opt_box_autoadd_record_list_prim_u_8_strict_list_pose_state(
          dynamic raw);

  @protected
  PoseState dco_decode_pose_state(dynamic raw);

  @protected
  (Uint8List, List<PoseState>)
      dco_decode_record_list_prim_u_8_strict_list_pose_state(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  PoseState sse_decode_box_autoadd_pose_state(SseDeserializer deserializer);

  @protected
  (Uint8List, List<PoseState>)
      sse_decode_box_autoadd_record_list_prim_u_8_strict_list_pose_state(
          SseDeserializer deserializer);

  @protected
  List<PoseState> sse_decode_list_pose_state(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  (Uint8List, List<PoseState>)?
      sse_decode_opt_box_autoadd_record_list_prim_u_8_strict_list_pose_state(
          SseDeserializer deserializer);

  @protected
  PoseState sse_decode_pose_state(SseDeserializer deserializer);

  @protected
  (Uint8List, List<PoseState>)
      sse_decode_record_list_prim_u_8_strict_list_pose_state(
          SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_pose_state(
      PoseState self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_record_list_prim_u_8_strict_list_pose_state(
      (Uint8List, List<PoseState>) self, SseSerializer serializer);

  @protected
  void sse_encode_list_pose_state(
      List<PoseState> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_record_list_prim_u_8_strict_list_pose_state(
      (Uint8List, List<PoseState>)? self, SseSerializer serializer);

  @protected
  void sse_encode_pose_state(PoseState self, SseSerializer serializer);

  @protected
  void sse_encode_record_list_prim_u_8_strict_list_pose_state(
      (Uint8List, List<PoseState>) self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
