// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'utils.freezed.dart';

@freezed
sealed class PoseState with _$PoseState {
  const PoseState._();

  const factory PoseState.good() = PoseState_Good;
  const factory PoseState.nobody() = PoseState_Nobody;
  const factory PoseState.pointsCountError(
    BigInt field0,
  ) = PoseState_PointsCountError;
  const factory PoseState.headOffsetTooMuch() = PoseState_HeadOffsetTooMuch;
  const factory PoseState.headInclinedTooMuch() = PoseState_HeadInclinedTooMuch;
  const factory PoseState.shoulderHeightDiffTooMuch() =
      PoseState_ShoulderHeightDiffTooMuch;
  const factory PoseState.spineAlignment() = PoseState_SpineAlignment;
  const factory PoseState.leftArmAngleNotGood() = PoseState_LeftArmAngleNotGood;
  const factory PoseState.rightArmAngleNotGood() =
      PoseState_RightArmAngleNotGood;
  const factory PoseState.leftLegAngleNotGood() = PoseState_LeftLegAngleNotGood;
  const factory PoseState.rightLegAngleNotGood() =
      PoseState_RightLegAngleNotGood;
}
